taxonomy = {
 'gerente': ['DIRECTIVOS'],
 'competidores': ['COMPETENCIA'],
 'jefe': ['DIRECTIVOS'],
 'publicidad': ['IMAGEN_DE_MARCA'],
 'opinion online': ['IMAGEN_DE_MARCA'],
 'competidoras': ['COMPETENCIA'],
 'campaña de marketing': ['IMAGEN_DE_MARCA'],
 'director general': ['DIRECTIVOS'],
 'competidor': ['COMPETENCIA'],
 'i+d': ['INNOVACION'],
 'competencia': ['COMPETENCIA'],
 'meses de garantia': ['CALIDAD'],
 'imagen de marca': ['IMAGEN_DE_MARCA'],
 'spot publicitario': ['IMAGEN_DE_MARCA'],
 'innovacion': ['INNOVACION'],
 'relacion calidad/precio': ['CALIDAD'],
 'investigacion': ['INNOVACION'],
 'competidora': ['COMPETENCIA'],
 'confianza': ['CALIDAD'],
 'campaña de publicidad': ['IMAGEN_DE_MARCA'],
 'competitividad': ['COMPETENCIA'],
 'relacion calidad y precio': ['CALIDAD'],
 'seguridad': ['CALIDAD'],
 'ceo': ['DIRECTIVOS'],
 'investigacion y desarrollo': ['INNOVACION'],
 'garantia': ['CALIDAD'],
 'director': ['DIRECTIVOS'],
 'relacion calidad precio': ['CALIDAD'],
 'empresas competidoras': ['COMPETENCIA'],
 'relacion calidad / precio': ['CALIDAD'],
 'innovacion y desarrollo': ['INNOVACION'],
 'representante': ['DIRECTIVOS'],
 'directora': ['DIRECTIVOS'],
 'años de garantia': ['CALIDAD'],
 'i+d+i': ['INNOVACION'],
 'reputacion': ['IMAGEN_DE_MARCA'],
 'calidad': ['CALIDAD'],
 'anuncios': ['IMAGEN_DE_MARCA'],
 'anuncio': ['IMAGEN_DE_MARCA'],
 'gestor': ['DIRECTIVOS'],
 'relacion calidad-precio': ['CALIDAD'],
 'futbol': ['FUTBOL'],
 'futbolista': ['FUTBOL'],
 'futbolistas': ['FUTBOL'],
 'jugador': ['FUTBOL'],
 'jugadores': ['FUTBOL'],
 'gol': ['FUTBOL'],
 'goles': ['FUTBOL'],
 'partido': ['FUTBOL'],
 'partidos': ['FUTBOL'],
 'liga': ['FUTBOL'],
 'copa': ['FUTBOL'],
 'champion': ['FUTBOL'],
 'portero': ['FUTBOL'],
 'defensa': ['FUTBOL'],
 'porteros': ['FUTBOL'],
 'defensas': ['FUTBOL'],
 'arbitro': ['FUTBOL'],
 'arbitros': ['FUTBOL'],
 'falta': ['FUTBOL'],
 'penalty': ['FUTBOL'],
 'fuera de juego': ['FUTBOL'],
 'corner': ['FUTBOL'],
 'balon': ['FUTBOL'],
 'pelota': ['FUTBOL'],
 'vestuario': ['FUTBOL'],
 'petroleo': ['COMBUSTIBLE'],
 'gasolina': ['COMBUSTIBLE'],
 'diesel': ['COMBUSTIBLE'],
 'gasoleo': ['COMBUSTIBLE'],
 'gas': ['COMBUSTIBLE'],

}
